export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';
export const GET_MENU_ITEMS_SUCCESS = 'GET_MENU_ITEMS_SUCCESS';
export const GET_MENU_ITEMS_FAILED = 'GET_MENU_ITEMS_FAILED';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const TOGGLE_DISABLE = 'TOGGLE_DISABLE';
export const TOGGLE_DISABLE_SUCCESS = 'TOGGLE_DISABLE_SUCCESS';
export const TOGGLE_DISABLE_FAILED = 'TOGGLE_DISABLE_FAILED';
export const RESET_MENU_MESSAGE = 'RESET_MENU_MESSAGE';
